Add capability to filter diagnostic entities
DigiLive/mushroom-strategy pull request #153
Opened 2024-11-09 19:05 UTC by w531t4

This PR enhances the existing functionality by allow a user to filter out diagnostic entities from a given domain, using the same logic previously used to filter configuration entities. 

Diagnostic entities clutter my dashboard, this gets rid of them.

```
...
    domains:
      _:
        hide_config_entities: true
        hide_diagnostic_entities: true <----
...
```

I am certainly no typescript expert, please treat this PR as if a idiot submitted it.

This functionality was requested in issue #127

Thanks!

2025-01-06 09:38 UTC, 0xFEEDC0DE64 commented
Since this won't get merged and the branch is already quite outdated, I did my best to do the conflicted rebase:
https://github.com/0xFEEDC0DE64/mushroom-strategy

2025-01-06 09:57 UTC, DigiLive commented
Thanks for the effort.

This PR waits on other PR's which needs to be merged first.
Until then, rebasing and merging preliminary has not much use.

2025-01-06 11:15 UTC, 0xFEEDC0DE64 commented
what other MR do need to be merged first?
can we please get all of this going, this dashboard generator is almost perfect, but it clutters all my areas with lots of useless entities like esphome free ram, signal strenghts and so on, I really need configs and diagnostics to be hidden by default like the homeassistant default dashboard already does

2025-01-06 12:28 UTC, DigiLive commented
You do realize this is something we do for free/voluntarily in our spare time in between jobs, other projects and personal live?
Also, we have to be careful not to break the scripts by merging PR's blindly into the `main` branch.
"No conflicts" doesn't mean a merge won't make unexpected (breaking) changes.

I do understand the desire of having an option to hide config/diagnostic entities with a simple setting. Since we already allow to hide config-entities, I will try to prioritize this PR.

In the meanwhile...
Hiding config-entities per domain or for all domains:
https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#domains

There's also the option to hide cards per entity: 
https://github.com/AalianKhan/mushroom-strategy/wiki/Adding-and-Hiding-entities-and-devices#adding-devices-to-areas
https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#card-options

It takes some time to set the configuration for now, but if you really, really need to hide config/diagnostic entities, you can.

2025-03-09 14:49 UTC, DigiLive requested changes
I've changed the way these entities are excluded from the dashboard.
Please verify if the correct entities are still hidden.

Also, The hidden `config` and `diagnostic` entities are still counted at the controller cards ~~, which I still have to address~~.

> [!NOTE]
> Option `hide_diagnostic_entities` has to be added to the Wiki as an "All domains" and "Per domain" option.

2025-03-11 03:36 UTC, AalianKhan commented
- Error when `domains` is equal to null. Or if any other domain under domains is equal to null including `_`
- in `translations/en.json` line 45 should have space in media players

Other than that, it is hiding the correct entities on my system.

2025-03-11 03:37 UTC, AalianKhan requested changes
- Error when `domains` is equal to null. Or if any other domain under `domains` is equal to null including _
- in translations/en.json line 45 should have space in media players

Other than that, it is hiding the correct entities on my system.

2025-03-11 06:03 UTC, DigiLive commented
> Error when `domains` is equal to null. Or if any other domain under `domains` is equal to null including _

Whenever is `domains` going to be `null`?
I need some more details, like when the error occurs, file, line, etc.

> in translations/en.json line 45 should have space in media players

This unrelated to this PR. You should open another issue or PR for that.

2025-03-17 01:16 UTC, AalianKhan commented
Well, domain isn't supposed to be null but if it is null because of user error, then the strategy errors out and doesn't give a useful error message either. It will be ideal for a check to be implemented before you try to read domains.

I will create a new pr for the language typo

2025-03-17 07:03 UTC, DigiLive commented
Even in case of a (user) configuration error, all supported domains do exist because of the configuration defaults.
If the user configures a non-existing/unsupported domain, the code will show an error in the console: `An error occurred while creating the domain cards!`

We can add code to validate the configuration, but that would be another issue/PR also.

2025-03-19 12:30 UTC, 0xFEEDC0DE64 commented
i have rebased the branch once again to include the german translations and other improvements :)
https://github.com/0xFEEDC0DE64/mushroom-strategy

2025-03-21 04:37 UTC, AalianKhan approved these changes

2025-03-23 06:28 UTC, DigiLive approved these changes

2025-03-23 06:33 UTC, merged