Add device subviews
DigiLive/mushroom-strategy pull request #155
Opened 2024-11-10 19:56 UTC by mwasilak

Add support for device subviews. User can add subviews for selected devices by specifying them in configuration. For such devices only specified entity cards are displayed in Area subview, other cards are accessible on newly added device subview.

Motivation:
- avoiding clutter on area subviews
- hiding rarely used functionalities (z-wave pings, obscure options, power meters)

2025-02-16 18:44 UTC, AalianKhan requested changes
Thanks a lot for your contribution! It really improves the readability of the overall Dashboard.

To keep the auto theme going. Should devices with more than 4 or so entities be automatically turned into devices with subview? and have an option if the user wants it to be seperate? What do you think @DigiLive?

2025-02-16 18:44 UTC, AalianKhan commented on src/mushroom-strategy.ts
> +    const devicesWithSubviews = Helper.strategyOptions.devices ?? {};
[Card Options](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#card-options) allows you to list device ids for card configuration. Instead of creating a new option, it is better to extend CustomCardConfig and add the deviceSubView option to it.

2025-02-17 14:18 UTC, DigiLive commented
I didn't had the opportunity to look into this PR.

However, since it conflicts with the `main` branch, I'd suggest to put it on hold until #164 and #176 are closed.
Then update this branch to resolve the conflicts with the `main` branch and from there start evaluating this PR.

2025-04-05 08:00 UTC, DigiLive reviewed
The code has derived to far from the `main` branch.
Too many conflict to resolve.

I'll pickup this PR to implement device sub views.

2025-04-05 08:02 UTC, DigiLive requested changes
The code has derived to far from the `main` branch.
Too many conflict to resolve.

I'll pickup this PR to implement device sub views.

2025-04-05 19:15 UTC, mwasilak commented
I'm closing the request. BTW area dashboards have been added in HA 2025.4 which cover similar functionality. I have switched to vanilla HA dashboards for now.

2025-04-05 19:15 UTC, closed without merging