Add Magic areas 2
DigiLive/mushroom-strategy pull request #75
Opened 2023-10-22 13:14 UTC by adrienbrault

Hey,

This PR contains https://github.com/AalianKhan/mushroom-strategy/pull/44 rebased, along with some refactoring based on @DigiLive's [comment](https://github.com/AalianKhan/mushroom-strategy/pull/44#pullrequestreview-1633369922).

Here's what it looks like on my dashboard:

<img src='https://github.com/AalianKhan/mushroom-strategy/assets/611271/82bb9f36-d9d4-490f-94f7-eb301c8d2c25' width='400'>

2023-10-24 08:47 UTC, adrienbrault commented
@DigiLive I've updated the branch with your suggestions.

I think the configuration format should be improved though

2023-10-24 10:33 UTC, DigiLive commented
> I think the configuration format should be improved though

Which format of which configuration do you suggest to what? Do you have a code example?

2023-10-24 13:58 UTC, DigiLive requested changes

2023-10-24 13:58 UTC, DigiLive commented on src/Helper.js
> +          if (deviceClass
Can the return conditions rewritten to a ternary operator statement?
E.g.: `return deviceClass && state.attributes.device_class === deviceClass ? state.entity_id.startsWith(`${domain}.`) : false;`

2023-10-24 13:58 UTC, DigiLive commented on src/Helper.js
> +  static getStateEntities(area, domain, deviceClass = null) {
`deviceClass = null` or `deviceClass = undefined`?

2023-10-24 13:58 UTC, DigiLive commented on src/Helper.js
> +            && state.attributes.device_class !== deviceClass
Unresolved variable device_class.

It should be included in typedef `stateObject` in file `src/typedefs.js`

2023-10-24 13:58 UTC, DigiLive commented on src/cards/AreaCard.js
> +      const temperatureSensorId = this.options?.temperature || Helper.getStateEntities(this.entity, "sensor", "temperature")[0]?.entity_id;
The type of field `options` in `AbstractClass` should change to `{abstractOptions & Object<string, any>}` to allow unknown additional properties.

Applies to lines #L70, #L71, #L72, #L92, #L93, #L94.

2023-10-24 13:58 UTC, DigiLive commented on src/cards/AreaCard.js
> +      const temperatureSensorId = this.options?.temperature || Helper.getStateEntities(this.entity, "sensor", "temperature")[0]?.entity_id;
Argument type  `hassEntity | areaEntity` is not assignable to parameter type `areaEntity`.

Maybe it's more proper to declare private field `#entity `in `AreaCard` as type `areaEntity` and assign in the value of parameter `area` in the constructor. And then use `this.#entity` in the function call of `Helper.getStateEntities`

Applies to lines #L70, #L71, #L72, #L92, #L93, #L94.

2023-10-24 14:03 UTC, DigiLive commented on src/Helper.js
> +   * @param {string|null} deviceClass Device class attribute of the state.
`deviceClass` should be `[deviceClass]` if it's an optional parameter.

2023-10-24 14:09 UTC, DigiLive commented
Please remove `./dist/mushroom-strategy.js` from your commits.
It will create a merge conflict. The file will be build at GitHub when an applicable PR is merged into the `main branch`.

2023-11-22 20:33 UTC, DigiLive commented
> [!WARNING]
> The `main` branch has been switched to TypeScript.
> Update your feature branch accordingly!

2023-12-19 09:59 UTC, closed without merging